First release
pagopa/pn-helpdesk-fe pull request #3
Opened 2022-11-04 10:33 UTC by acolella92

2022-11-08 11:00 UTC, ZorbaDimatteo requested changes

2022-11-08 11:01 UTC, ZorbaDimatteo commented
@acolella92 a general formatting for code is necessary

2022-11-15 11:20 UTC, acolella92 commented on src/pages/monitor/MonitorPage.tsx
> +      <h1>Monitor page</h1>
This is just a placeholder for monitor page, will be solved once the monitor page code will be merged

2022-11-15 11:20 UTC, acolella92 commented on src/navigation/Router.tsx
> +  const [email, setEmail] = useState("test@test.com");
Changed to empty string and pushed

2022-11-15 13:14 UTC, ZorbaDimatteo approved these changes

2022-11-15 13:17 UTC, merged