feat: added prettier and eslint
pagopa/pn-helpdesk-fe pull request #59
Opened 2023-07-26 06:56 UTC by alessandrogelmi

Added Prettier in order to format all code.
Also added ESLint and fixed all errors about it

2023-08-22 07:52 UTC, clombardi requested changes
The rework is in general OK in my opinion. In particular, I haven't found any change that could compromise the functionality. I underlined several details that could be worked to further improve the code quality.

I proceeded mostly by static code analysis, I only checked against the running app in a couple of cases in which I had doubts about the proposed code behavior. In any case, IMHO this PR should undergo extensive manual testing from our colleagues of the QC team.

2023-08-22 07:52 UTC, clombardi commented on src/redux/tender/reducers.tsx
> -        force: !!(state.pagination.force) ? !state.pagination.force : true
I guess this equals to just `!state.pagination.force`. Please check *only* if testing is feasible.

2023-08-25 06:27 UTC, alessandrogelmi commented on src/Authentication/auth.tsx
> +        user.refreshSession(refreshToken!, async () => {
Beacause inside the function there's a Promise (setStorage)

2023-08-25 06:31 UTC, alessandrogelmi commented on .prettierrc.js
> +module.exports = {
I think that .prettierrc.js is useless. I also checked pn-frontend and i noticed that both file are present

2023-08-25 06:38 UTC, alessandrogelmi commented on src/components/buttonsGroup/ButtonsActionCostTable.tsx
> +              <EditIcon fontSize="small" />
I think that double quote is right because is an HTML attribute. Also verified on pn-frontend

2023-08-25 06:40 UTC, alessandrogelmi commented on src/components/confirmationDialog/ConfirmationDialog.tsx
> +        <DialogContentText id="alert-dialog-description" data-testid="dialog-description">
I think that double quote is right because is an HTML attribute. Also verified on [pn-frontend](https://github.com/pagopa/pn-frontend)

2023-08-25 06:40 UTC, alessandrogelmi commented on src/components/dataInfo/DataInfo.tsx
> +        <Grid key={row.id} item container direction="row" width="1">
I think that double quote is right because is an HTML attribute. Also verified on [pn-frontend](https://github.com/pagopa/pn-frontend)

2023-08-25 06:45 UTC, alessandrogelmi commented on src/components/deliveriesDrivers/TenderTable.tsx
> +    // eslint-disable-next-line
I removed the comment and added a void

2023-08-25 06:53 UTC, alessandrogelmi commented on src/components/forms/deliveryDriver/DeliveryDriverForm.tsx
> +            <Typography variant="h5" component="div">
I think that double quote is right because is an HTML attribute. Also verified on [pn-frontend](https://github.com/pagopa/pn-frontend)

2023-08-25 06:53 UTC, alessandrogelmi commented on src/components/forms/download/DownloadForm.tsx
> +          <Typography variant="h4">Download</Typography>
I think that double quote is right because is an HTML attribute. Also verified on [pn-frontend](https://github.com/pagopa/pn-frontend)

2023-08-25 06:54 UTC, alessandrogelmi commented on src/components/forms/filterTable/FilterTable.tsx
> +              variant="outlined"
I think that double quote is right because is an HTML attribute. Also verified on [pn-frontend](https://github.com/pagopa/pn-frontend)

2023-08-25 06:55 UTC, alessandrogelmi commented on src/components/forms/search/SearchForm.tsx
> +        // eslint-disable-next-line
I used void and removed comment

2023-08-25 07:01 UTC, alessandrogelmi commented on src/components/header/Header.tsx
> +              <Typography align="center" color="primary.contrastText">
Don't think so. Simply we have always used double quotes.

2023-08-25 07:03 UTC, alessandrogelmi commented on src/components/responseData/ResponseData.tsx
> +              {ResponseType[Object.keys(response)[0] as keyof typeof ResponseType]}:{' '}
Yes, but now I implemented it with template literals

2023-08-25 07:09 UTC, alessandrogelmi commented on src/hooks/__test__/usePagination.test.tsx
> +import 'regenerator-runtime/runtime';
I've deleted the file since there're not tests inside

2023-08-25 08:41 UTC, clombardi commented on src/Authentication/auth.tsx
> +        user.refreshSession(refreshToken!, async () => {
OK, you're right and I was wrong. But I have to say that the way in which session storage access functions are (IMHO) artificially embedded in Promises is indeed strange to me. Session storage handling is sync.

2023-08-25 08:52 UTC, clombardi commented on src/components/deliveriesDrivers/TenderTable.tsx
> +    // eslint-disable-next-line
OK, maybe you could do analogously in `src/components/deliveriesDrivers/DeliveriesDriverTable.tsx`

2023-08-25 09:37 UTC, clombardi commented on .prettierrc.js
> +module.exports = {
We'll raise the issue to the #team-frontend-pn Slack channel

2023-08-25 10:06 UTC, alessandrogelmi commented on .prettierrc.js
> +module.exports = {
As decided on Slack I've removed `.prettierrc.js` file

2023-08-25 12:49 UTC, clombardi approved these changes
OK, finally ... ready to merge!!!

2023-08-25 12:49 UTC, merged